name: Validate Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli --global

      - name: Authenticate with DevOrg
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL_DEV }}
        run: |
          echo $SFDX_AUTH_URL | sfdx auth:sfdxurl:store -f -

      - name: Authenticate with PRODOrg
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL_PROD }}
        run: |
          echo $SFDX_AUTH_URL | sfdx auth:sfdxurl:store -f -

      - name: Validate against PRODOrg
        run: |
          sfdx force:source:deploy -p force-app -u PRODOrg -l RunLocalTests
